name: Java CI with Gradle

on:
  pull_request:
    branches: [ master ]

jobs:
  natives-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Install build dependencies and cross-compilation toolchains
      run: |
        sudo apt update
        sudo apt install -y --force-yes gcc g++
        sudo apt install -y --force-yes nasm

    - name: Build natives with Gradle
      run: ./gradlew :gdx-video-desktop:buildFFmpegLinux64 :gdx-video-desktop:jnigenBuildLinux64

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: desktop-natives
        path: gdx-video-desktop/libs/**/*.so
        if-no-files-found: error

  natives-windows:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Install build dependencies and cross-compilation toolchains
      run: |
        sudo apt update
        sudo apt install -y --force-yes nasm
        sudo apt install -y --force-yes mingw-w64 lib32z1

    - name: Build natives with Gradle
      run: ./gradlew :gdx-video-desktop:buildFFmpegWindows64 :gdx-video-desktop:jnigenBuildWindows64

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: desktop-natives
        path: gdx-video-desktop/libs/**/*.dll
        if-no-files-found: error
